# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './.compileui/mixer.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MixerWidget(object):
    def setupUi(self, MixerWidget):
        MixerWidget.setObjectName("MixerWidget")
        MixerWidget.resize(100, 430)
        self.widget = Ui_VUMeterWidget(MixerWidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 50, 430))
        self.widget.setObjectName("widget")

        self.retranslateUi(MixerWidget)
        QtCore.QMetaObject.connectSlotsByName(MixerWidget)

    def retranslateUi(self, MixerWidget):
        _translate = QtCore.QCoreApplication.translate
        MixerWidget.setWindowTitle(_translate("MixerWidget", "Form"))
from ui_vumeter import Ui_VUMeterWidget
