# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './.compileui/vumeter.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VuMeterWidget(object):
    def setupUi(self, VuMeterWidget):
        VuMeterWidget.setObjectName("VuMeterWidget")
        VuMeterWidget.resize(50, 430)
        VuMeterWidget.setStyleSheet("")
        self.GradientLeft = QtWidgets.QWidget(VuMeterWidget)
        self.GradientLeft.setGeometry(QtCore.QRect(0, -1, 20, 431))
        self.GradientLeft.setStyleSheet("background-color: qlineargradient(spread:pad, \n"
"x1:0,\n"
"y1:1, \n"
"x2:0, \n"
"y2:0, \n"
"stop:0 rgba(0, 255, 0, 255),\n"
"stop:0.75 rgba(255,255,0,255), \n"
"stop:1 rgba(255, 0, 0, 255));")
        self.GradientLeft.setObjectName("GradientLeft")
        self.GradientRight = QtWidgets.QWidget(VuMeterWidget)
        self.GradientRight.setGeometry(QtCore.QRect(30, 0, 20, 431))
        self.GradientRight.setStyleSheet("background-color: qlineargradient(spread:pad, \n"
"x1:0,\n"
"y1:1, \n"
"x2:0, \n"
"y2:0, \n"
"stop:0 rgba(0, 255, 0, 255),\n"
"stop:0.75 rgba(255,255,0,255), \n"
"stop:1 rgba(255, 0, 0, 255));")
        self.GradientRight.setObjectName("GradientRight")

        self.retranslateUi(VuMeterWidget)
        QtCore.QMetaObject.connectSlotsByName(VuMeterWidget)

    def retranslateUi(self, VuMeterWidget):
        _translate = QtCore.QCoreApplication.translate
        VuMeterWidget.setWindowTitle(_translate("VuMeterWidget", "Form"))
